services:
  postgres_db:
    container_name: postgres_db_job
    image: postgres:14-alpine3.18
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: job_db
    ports:
      - "5434:5432"
    volumes:
      - volume_postgres_db_data:/var/lib/postgresql/data
    healthcheck:
      test: "pg_isready -U postgres | grep 'accepting connections' || exit 1"
      interval: 2s
      timeout: 20s
      retries: 10
volumes:
  volume_postgres_db_data:
    external: false